name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [win,linux,osx]
        include:
          - platform: win
            matrix:
              architecture: [x86,x64,arm64]
          - platform: osx
            matrix:
              architecture: [x64]
          - platform: linux
            matrix:
              architecture: [x64,arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.101"

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build CLI utilities
        shell: pwsh
        run: |
          msbuild /m /t:restore,cli\uupmediaconvertercli:publish,cli\uupdownload:publish,cli\uupmediaconverterdismbroker:publish /p:Platform=${{ matrix.architecture }} /p:RuntimeIdentifier=${{ matrix.platform }}-${{ matrix.architecture }} /p:PublishDir=${{ github.workspace }}/artifacts/${{ matrix.platform }}-${{ matrix.architecture }}/CLI /p:PublishSingleFile=true /p:PublishTrimmed=false /p:Configuration=Release UUPMediaCreator.sln

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform }}-${{ matrix.architecture }}
          path: ${{ github.workspace }}/artifacts/${{ matrix.platform }}-${{ matrix.architecture }}
